# Generated by Django 4.1.7 on 2023-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='exist',
            field=models.CharField(default=1973, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='company',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
